// Generated by CoffeeScript 1.10.0
(function() {
  var median,
    slice = [].slice;

  median = function() {
    var input_array, posetion, result, size;
    input_array = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    size = input_array.length;
    posetion = 0;
    result = 0;
    if (size % 2 !== 0) {
      posetion = (size - 1) / 2;
      result = input_array[posetion];
    } else {
      posetion = size / 2;
      result = (input_array[posetion] + input_array[posetion - 1]) / 2;
    }
    return result;
  };

}).call(this);

//# sourceMappingURL=median.js.map
