// Generated by CoffeeScript 1.10.0
(function() {
  var sum,
    slice = [].slice;

  sum = function() {
    var count, i, input_array, len, total;
    input_array = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    total = 0;
    for (i = 0, len = input_array.length; i < len; i++) {
      count = input_array[i];
      total += count;
    }
    return total;
  };

}).call(this);

//# sourceMappingURL=sum.js.map
