// Generated by CoffeeScript 1.10.0
(function() {
  var max, x,
    slice = [].slice;

  max = function() {
    var input_array;
    input_array = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return Math.max.apply(Math, input_array);
  };

  x = [-10];

  console.log(max.apply(null, x));

}).call(this);

//# sourceMappingURL=max.js.map
