// Generated by CoffeeScript 1.10.0
(function() {
  var min, x,
    slice = [].slice;

  min = function() {
    var input_array;
    input_array = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return Math.min.apply(Math, input_array);
  };

  x = [-10];

  console.log(min.apply(null, x));

}).call(this);

//# sourceMappingURL=min.js.map
