// Generated by CoffeeScript 1.10.0
(function() {
  var join, x,
    slice = [].slice;

  x = [2, 3, 6, 8, 4, 2, 6, 9];

  join = function() {
    var input_array, key, n, result, value;
    input_array = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    n = input_array.length;
    result = [];
    for (key in input_array) {
      value = input_array[key];
      result.push([value, value + n / 2]);
    }
    return result;
  };

  console.log(join.apply(null, x));

}).call(this);

//# sourceMappingURL=join.js.map
